spring:
  application:
    name: classifier
  datasource:
    username: zakat
    password: zakat_pwd
    url: jdbc:postgresql://localhost:5432/classifier
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    enabled: true

s3:
  region: ${S3_REGION}
  endpoint-url: ${S3_ENDPOINT_URL}
  bucket: ${S3_BUCKET}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        boot:
          autoconfigure:
            flyway: DEBUG
