spring:
  application:
    name: classifier
  datasource:
    username: zakat
    password: zakat_pwd
    url: jdbc:postgresql://localhost:5432/classifier
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    enabled: true

logging:
  level:
    org:
      flywaydb: DEBUG
      springframework:
        boot:
          autoconfigure:
            flyway: DEBUG
